version: '3.1'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: admin
    restart: always
    volumes:
      - ./mysqldb:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
volumes:
  mysqldb: