services:
  kafka:
    extends:
      file: parts/kafka-cluster.yml
      service: kafka
    networks:
      - ${NETWORK_NAME}
  kafka2:
    extends:
      file: parts/kafka-cluster.yml
      service: kafka2
    networks:
      - ${NETWORK_NAME}
  kafka3:
    extends:
      file: parts/kafka-cluster.yml
      service: kafka3
    networks:
      - ${NETWORK_NAME}
  zookeeper:
    extends:
      file: parts/kafka-cluster.yml
      service: zookeeper
    networks:
      - ${NETWORK_NAME}
  kafka-ui:
    extends:
      file: parts/kafka-cluster.yml
      service: kafka-ui
    networks:
      - ${NETWORK_NAME}
networks:
  telematic:
    name: ${NETWORK_NAME}
    external: ${IS_NETWORK_EXTERNAL}
