version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=admin
    restart: always
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysqldb
